Repository charmbracelet/bubbles, pull requests merged in 2024-10, with the labels that each got.

#574 feat(list): implement GlobalIndex helper
  list/list.go
Labels: enhancement

#554 fix(help): wrong full help sep rendering
  help/help.go
Labels: bug

#619 (v2) refactor!: viewport: remove deprecated HighPerformanceRendering
  go.mod
  go.sum
  viewport/viewport.go
Labels: v2
