Repository charmbracelet/bubbles, pull requests merged in 2025-01, with the labels that each got.

#240 feat(viewport): horizontal scroll
  go.mod
  go.sum
  viewport/keymap.go
  viewport/viewport.go
  viewport/viewport_test.go
Labels: enhancement

#583 docs: additional bubbles
  README.md
Labels: documentation

#703 docs: update charm & friends blurb
  README.md
Labels: documentation

#706 fix(viewport): scroll to last line when borders
  viewport/viewport.go
Labels: bug

#709 (v2) Revert cursor position from v2-area
  textarea/textarea.go
Labels: v2

#682 Don't render suggestions when textinput is not focused.
  textinput/textinput.go
  textinput/textinput_test.go
Labels: enhancement
