Repository charmbracelet/bubbles, pull requests merged in 2025-03, with the labels that each got.

#753 fix(filepicker): properly scrolling filepicker
  filepicker/filepicker.go
Labels: bug

#705 docs: add example for ValidateFunc
  textinput/textinput_test.go
Labels: documentation

#763 fix(viewport): normalize method names
  textarea/textarea.go
  textarea/textarea_test.go
  viewport/viewport.go
  viewport/viewport_test.go
Labels: enhancement

#765 fix(viewport): normalize method names
  table/table.go
  textarea/textarea.go
  textarea/textarea_test.go
  viewport/viewport.go
  viewport/viewport_test.go
Labels: enhancement

#767 fix(textarea): placeholder with chinese chars
  go.mod
  textarea/textarea.go
  textarea/textarea_test.go
Labels: bug
